# Generated by Django 3.2.5 on 2021-07-27 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210727_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=30)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.video')),
            ],
        ),
    ]
