# Generated by Django 3.2.5 on 2021-08-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210803_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='like_or_dislike',
            field=models.IntegerField(help_text='1 for like 0 for dislike'),
        ),
        migrations.AlterField(
            model_name='videoview',
            name='session_key',
            field=models.CharField(max_length=32),
        ),
    ]
