# Generated by Django 3.2.5 on 2021-08-09 20:36

import MetioTube.core.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210807_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[
                MetioTube.core.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[
                MetioTube.core.validators.validate_video_file]),
        ),
    ]
