# Generated by Django 3.2.5 on 2021-07-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metio_tube_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(default='../static/images/default_profile.jpg', upload_to='profiles')),
                ('about', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='metio_tube_auth.metiotubeuser')),
            ],
        ),
    ]
