# Generated by Django 3.2.5 on 2021-07-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metio_tube_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metiotubeuser',
            name='username',
        ),
    ]
