# Generated by Django 3.2.5 on 2021-08-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metio_tube_auth', '0002_remove_metiotubeuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metiotubeuser',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='metiotubeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
